import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { LogoRight } from "./_components/LogoRight";
import { LogoLeft } from "./_components/LogoLeft";
import { Curve } from "./_components/Curve";
import { Ring } from "./_components/Ring";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  // const circles = [
  //   "w-[1340px] h-[1340px]",
  //   "w-[940px] h-[940px]",
  //   "w-[540px] h-[540px]",
  //   "w-[340px] h-[340px]",
  //   "w-[140px] h-[140px]",
  // ];
  // return (
  //   <html lang="en">
  //     <body
  //       className={`${geistSans.variable} ${geistMono.variable} antialiased flex items-center justify-center h-screen`}
  //     >
  //       <div className="relative w-[1600px] h-[1200px] flex justify-center items-center">
  //         {children}
  //         {circles.map((el, index) => {
  //           return <Ring key={index} el={el} />;
  //         })}
  //         <Curve />
  //         <LogoLeft />
  //         <LogoRight />
  //       </div>
  //     </body>
  //   </html>
  // );
}
